version: '3'
services:
    app:
        build: .
        image: yifan20000/node-web-app
        volumes:
            - .:/usr/src/app
        restart: always
        ports:
            - 3040:3040

